import uuid
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, HttpUrl
from sqlalchemy import Column, String, Text, DateTime, Float, Boolean, ForeignKey
from sqlalchemy.orm import declarative_base, relationship

# ---------------------------------------------------------------------------
# SQLAlchemy ORM Models
# ---------------------------------------------------------------------------
Base = declarative_base()

class DBArticle(Base):
    """
    SQLAlchemy ORM Model representing an ingested and processed news article.
    """
    __tablename__ = "articles"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    title = Column(String(512), nullable=False)
    url = Column(String(2048), nullable=False, unique=True, index=True)
    content = Column(Text, nullable=False)
    summary = Column(Text, nullable=True)
    category = Column(String(100), nullable=True, default="General", index=True)
    source = Column(String(255), nullable=True)
    content_hash = Column(String(64), nullable=False, index=True)
    vector_id = Column(String(64), nullable=True)
    is_verified = Column(Boolean, default=False)
    confidence_score = Column(Float, default=1.0)
    published_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    logs = relationship("DBProcessingLog", back_populates="article", cascade="all, delete-orphan")


class DBProcessingLog(Base):
    """
    SQLAlchemy ORM Model for recording agent processing execution logs.
    """
    __tablename__ = "processing_logs"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    article_id = Column(String(36), ForeignKey("articles.id"), nullable=False)
    step_name = Column(String(100), nullable=False)
    status = Column(String(50), nullable=False)  # e.g., "SUCCESS", "FAILED", "SKIPPED"
    log_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    article = relationship("DBArticle", back_populates="logs")


class DBUserSubscription(Base):
    """
    SQLAlchemy ORM Model tracking user topic subscriptions for scheduled daily digests.
    """
    __tablename__ = "user_subscriptions"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_phone = Column(String(50), nullable=False, index=True)
    topic = Column(String(100), nullable=False, index=True)  # e.g., "AI & Robotics", "Software & Tech", "Finance & Business", "All"
    digest_time = Column(String(10), default="08:00")  # HH:MM format
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)


# ---------------------------------------------------------------------------
# Pydantic Schemas / Data Transfer Objects
# ---------------------------------------------------------------------------
class ArticleBase(BaseModel):
    """Base Pydantic model for news article attributes."""
    title: str = Field(..., description="Headline title of the news article")
    url: str = Field(..., description="Canonical source URL of the article")
    content: str = Field(..., description="Extracted clean text content")
    source: Optional[str] = Field(None, description="News publisher or feed name")
    category: Optional[str] = Field("General", description="Topic category (Tech, AI, Finance, etc.)")
    published_at: Optional[datetime] = Field(None, description="Original publication timestamp")


class ArticleCreate(ArticleBase):
    """Payload for creating a new article."""
    content_hash: str = Field(..., description="SHA256 hash of normalized content for exact deduplication")


class ArticleResponse(ArticleBase):
    """API Response schema for an ingested/processed article."""
    id: str = Field(..., description="Unique UUID of the article")
    summary: Optional[str] = Field(None, description="Executive summary generated by agents")
    content_hash: str
    vector_id: Optional[str] = None
    is_verified: bool = False
    confidence_score: float = 1.0
    created_at: datetime

    class Config:
        from_attributes = True


class DuplicateCheckResult(BaseModel):
    """Data contract for vector deduplication results."""
    is_duplicate: bool = Field(..., description="True if article is exact hash or semantic vector duplicate")
    similarity_score: float = Field(..., description="Cosine similarity score (0.0 to 1.0)")
    matched_article_id: Optional[str] = Field(None, description="ID of existing matching article if duplicate")
    reason: str = Field(..., description="Explanation of deduplication verdict")


class IngestionResult(BaseModel):
    """Summary result of a news feed ingestion operation."""
    total_fetched: int = Field(0, description="Total stories found in feed")
    inserted_count: int = Field(0, description="New stories ingested into system")
    duplicate_count: int = Field(0, description="Duplicate stories filtered out")
    errors: List[str] = Field(default_factory=list, description="Error messages encountered during ingestion")


class SubscriptionCreate(BaseModel):
    """Payload for subscribing user to a topic."""
    user_phone: str = Field(..., description="User WhatsApp phone number")
    topic: str = Field("All", description="Topic category to subscribe to")
    digest_time: Optional[str] = Field("08:00", description="Preferred daily digest time (HH:MM)")


class SubscriptionResponse(BaseModel):
    """API response schema for user subscription."""
    id: str
    user_phone: str
    topic: str
    digest_time: str
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


class WhatsAppMessage(BaseModel):
    """Incoming WhatsApp message payload schema."""
    sender_id: str = Field(..., description="WhatsApp phone number of sender")
    message_body: str = Field(..., description="Text content of incoming message")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ConversationalResponse(BaseModel):
    """Structured response returned by conversational agent."""
    reply_text: str = Field(..., description="Text to send back to user")
    articles_referenced: List[ArticleResponse] = Field(default_factory=list, description="Articles used in reply")
    intent: str = Field("unknown", description="Detected user query intent")
    buttons: Optional[List[Dict[str, str]]] = Field(None, description="Optional interactive quick-reply buttons")
